### ISSUE TITLE
safeway-delivery-check purpose

### ISSUE THREAD

**Issue by runn753** [christru/safeway-delivery-check#1]
I'm looking for a script that will alert me when a slot is open for Safeway grocery delivery at www.safeway.com. My elderly in-laws live in NJ and depend on my wife (who lives in AZ) to order their groceries. She's been online ordering remotely for 2 years. But now with covid, the delivery slots are all gone whenever she checks. She is on all hours day and night and just happens to get lucky sometimes.

I thought this might do it but there's no mention of safeway at all except "Safeway has an available appointment to deliver your groceries!" Other than that, it looks like a test program. (I'm a programmer but haven't programmed for years. I look at your code and most of it looks foreign.)

So will this do what I'm looking for?

**Comment by christru** [comment]
Most definitely. But it's sort of badly documented/written. This was used successfully to secure a spot twice for me. I'm pretty busy and wanted to gauge interest in it before I cleaned it up or documented it at all. I had this run as a windows schedule task in a background and used a trial twilio account to alert me. Its uses a frontend testing framework to execute the test and if it succesful (finds any appointment on any day ) will shoot out a text.

**Comment by christru** [comment]
@runn753  Requires NodeJS
Clone repository
open command prompt
Navitate to safeway-delivery-check
npm install
Update variables
In wdio.conf.js
	Update YOURTWILIOSID to your twilioSid
	Update YOURTWILIOAUTHTOKEN to your AuthToken
In test/specs/basic.js
	Update SAFEWAYLOGIN to your Safeway login
	Update SAFEWAYPASSWORD to your Safeway password

Run the script by doing the following:
in command prompt: npx wdio wdio.conf.js

This can be setup to as a windows schedule task to run every 5 mins. (thats how I quickly set it up on lunch)

More info about webdriver can be found here:
https://webdriver.io/docs/gettingstarted.html
twilio here:https://www.twilio.com/
nodejs:https://nodejs.org/en/

**Comment by runn753** [comment]
First off, thanks for going to the trouble of answering me and throwing in
the how-to-run-it instructions to boot. But I'm embarrassed to say that
when I told my wife about this neat feature with safeway, she said she has
been ordering from shoprite!

So your script won't work for me out-of-the-box, but if you're ok with it,
I'll clone it and try to see if I can get something that works for shoprite.

**Comment by christru** [comment]
You are welcome. I’m 100 percent ok with that. Put it up here to help anyone that needed it. Goodluck!
